// Generated by scripts/build-subject-index.mjs from the files in this folder. Do not edit.
import appliedPhysicsSubject from "./applied-physics.json";
import basicElectricalSubject from "./basic-electrical.json";
import basicElectronicsSubject from "./basic-electronics.json";
import emSubject from "./em.json";
import enggChemistrySubject from "./engg-chemistry.json";
import enggGraphicsSubject from "./engg-graphics.json";
import enggMathSubject from "./engg-math.json";
import enggMechanicsSubject from "./engg-mechanics.json";
import environmentalScienceSubject from "./environmental-science.json";
import ppsSubject from "./pps.json";
import appliedPhysicsSources from "./applied-physics-sources.json";
import basicElectricalSources from "./basic-electrical-sources.json";
import basicElectronicsSources from "./basic-electronics-sources.json";
import emSources from "./em-sources.json";
import enggChemistrySources from "./engg-chemistry-sources.json";
import enggGraphicsSources from "./engg-graphics-sources.json";
import enggMathSources from "./engg-math-sources.json";
import enggMechanicsSources from "./engg-mechanics-sources.json";
import environmentalScienceSources from "./environmental-science-sources.json";
import ppsSources from "./pps-sources.json";

/** Every subject file, in file-name order. */
export const subjectFiles: unknown[] = [appliedPhysicsSubject, basicElectricalSubject, basicElectronicsSubject, emSubject, enggChemistrySubject, enggGraphicsSubject, enggMathSubject, enggMechanicsSubject, environmentalScienceSubject, ppsSubject];

/** Grounding sources per subject id (from <id>-sources.json). */
export const sourceFiles: Record<string, unknown> = {
  "applied-physics": appliedPhysicsSources,
  "basic-electrical": basicElectricalSources,
  "basic-electronics": basicElectronicsSources,
  "em": emSources,
  "engg-chemistry": enggChemistrySources,
  "engg-graphics": enggGraphicsSources,
  "engg-math": enggMathSources,
  "engg-mechanics": enggMechanicsSources,
  "environmental-science": environmentalScienceSources,
  "pps": ppsSources,
};
