// Generated by scripts/build-subject-light.mjs from the subject files. Do not edit.
/** Loads one subject's full data (chapters and topics) on demand, by subject id. */
export const subjectLoaders: Record<string, () => Promise<{ default: unknown }>> = {
  "advanced-communication-networks-communication-systems": () =>
    import("./advanced-communication-networks-communication-systems.json"),
  "advanced-data-structure-and-algorithms": () =>
    import("./advanced-data-structure-and-algorithms.json"),
  "advanced-drilling-technology": () => import("./advanced-drilling-technology.json"),
  "advanced-processors-and-socs-vlsi-embedded": () =>
    import("./advanced-processors-and-socs-vlsi-embedded.json"),
  "advanced-web-technology-software-and-networks": () =>
    import("./advanced-web-technology-software-and-networks.json"),
  "agent-based-learning": () => import("./agent-based-learning.json"),
  "agile-and-devops": () => import("./agile-and-devops.json"),
  "analog-communication": () => import("./analog-communication.json"),
  "analog-electronics": () => import("./analog-electronics.json"),
  "analog-ic-design-vlsi-embedded": () => import("./analog-ic-design-vlsi-embedded.json"),
  "analytical-bioinformatics": () => import("./analytical-bioinformatics.json"),
  "animal-and-plant-biotechnology": () => import("./animal-and-plant-biotechnology.json"),
  "applied-physics": () => import("./applied-physics.json"),
  "autonomous-systems": () => import("./autonomous-systems.json"),
  "basic-electronics": () => import("./basic-electronics.json"),
  "big-data-analytics": () => import("./big-data-analytics.json"),
  biochemistry: () => import("./biochemistry.json"),
  "bioethics-ipr-and-biosafety": () => import("./bioethics-ipr-and-biosafety.json"),
  "biological-systems-for-engineers": () => import("./biological-systems-for-engineers.json"),
  "biology-for-engineers-biotech": () => import("./biology-for-engineers-biotech.json"),
  "biology-for-engineers-ece-civil": () => import("./biology-for-engineers-ece-civil.json"),
  "biology-for-engineers-ict": () => import("./biology-for-engineers-ict.json"),
  "biomass-conversion-and-utilisation": () => import("./biomass-conversion-and-utilisation.json"),
  "biomaterial-and-implants": () => import("./biomaterial-and-implants.json"),
  "biophysics-and-structural-biology": () => import("./biophysics-and-structural-biology.json"),
  "bioprocess-engineering": () => import("./bioprocess-engineering.json"),
  "blockchain-technology-ce": () => import("./blockchain-technology-ce.json"),
  "blockchain-technology-software-and-networks-ict": () =>
    import("./blockchain-technology-software-and-networks-ict.json"),
  "building-materials-and-construction-technology": () =>
    import("./building-materials-and-construction-technology.json"),
  "building-planning-and-computer-aided-drawing": () =>
    import("./building-planning-and-computer-aided-drawing.json"),
  "carbon-utilization-and-storage": () => import("./carbon-utilization-and-storage.json"),
  "cheminformatics-and-medicinal-chemistry": () =>
    import("./cheminformatics-and-medicinal-chemistry.json"),
  "chemistry-ict": () => import("./chemistry-ict.json"),
  "chemistry-petro": () => import("./chemistry-petro.json"),
  "chemistry-theory-me": () => import("./chemistry-theory-me.json"),
  "city-gas-distribution": () => import("./city-gas-distribution.json"),
  "cloud-architecture-and-service-software-and-networks": () =>
    import("./cloud-architecture-and-service-software-and-networks.json"),
  "cloud-computing": () => import("./cloud-computing.json"),
  coa: () => import("./coa.json"),
  "compiler-design": () => import("./compiler-design.json"),
  "computer-aided-design-drawing-lab-i": () => import("./computer-aided-design-drawing-lab-i.json"),
  "computer-aided-design": () => import("./computer-aided-design.json"),
  "computer-aided-drug-design": () => import("./computer-aided-drug-design.json"),
  "computer-aided-manufacturing-cam-major-in-house-project": () =>
    import("./computer-aided-manufacturing-cam-major-in-house-project.json"),
  "computer-communication-and-networking": () =>
    import("./computer-communication-and-networking.json"),
  "computer-graphics": () => import("./computer-graphics.json"),
  "computer-networks-2": () => import("./computer-networks-2.json"),
  "computer-networks": () => import("./computer-networks.json"),
  "computer-organization-and-microprocessor-ece": () =>
    import("./computer-organization-and-microprocessor-ece.json"),
  "computer-organization-and-microprocessor-ict": () =>
    import("./computer-organization-and-microprocessor-ict.json"),
  "computer-programming-i-ce": () => import("./computer-programming-i-ce.json"),
  "computer-programming-i-ece-biotech": () => import("./computer-programming-i-ece-biotech.json"),
  "computer-programming-i-ict": () => import("./computer-programming-i-ict.json"),
  "computer-programming-i-petro": () => import("./computer-programming-i-petro.json"),
  "computer-programming-ii-ce": () => import("./computer-programming-ii-ce.json"),
  "computer-programming-ii-ece-biotech": () => import("./computer-programming-ii-ece-biotech.json"),
  "computer-programming-ii-ict": () => import("./computer-programming-ii-ict.json"),
  "computer-programming-ii-petro": () => import("./computer-programming-ii-petro.json"),
  "computer-vision": () => import("./computer-vision.json"),
  "concrete-technology": () => import("./concrete-technology.json"),
  "control-systems": () => import("./control-systems.json"),
  "corrosion-studies-in-petroleum-industry": () =>
    import("./corrosion-studies-in-petroleum-industry.json"),
  "cryptography-and-network-security-ce": () =>
    import("./cryptography-and-network-security-ce.json"),
  "cryptography-and-network-security-software-and-networks-ict": () =>
    import("./cryptography-and-network-security-software-and-networks-ict.json"),
  "cyber-laws-and-ethics": () => import("./cyber-laws-and-ethics.json"),
  "data-analytics-for-petroleum-engineers": () =>
    import("./data-analytics-for-petroleum-engineers.json"),
  "data-communication": () => import("./data-communication.json"),
  "data-mining-and-data-warehousing": () => import("./data-mining-and-data-warehousing.json"),
  "data-structures": () => import("./data-structures.json"),
  "database-management-systems-computer-systems-ece": () =>
    import("./database-management-systems-computer-systems-ece.json"),
  "database-management-systems-ict": () => import("./database-management-systems-ict.json"),
  dbms: () => import("./dbms.json"),
  "deep-learning-and-applications-computer-systems": () =>
    import("./deep-learning-and-applications-computer-systems.json"),
  "deep-learning": () => import("./deep-learning.json"),
  "dept-elective-i-non-conventional-energy-sources-course": () =>
    import("./dept-elective-i-non-conventional-energy-sources-course.json"),
  "dept-elective-ii-advance-manufacturing-process": () =>
    import("./dept-elective-ii-advance-manufacturing-process.json"),
  "design-and-analysis-of-algorithm": () => import("./design-and-analysis-of-algorithm.json"),
  "design-and-kinematics-of-machines": () => import("./design-and-kinematics-of-machines.json"),
  "design-of-rcc-structures": () => import("./design-of-rcc-structures.json"),
  "design-of-steel-structures": () => import("./design-of-steel-structures.json"),
  "digital-circuits-ict": () => import("./digital-circuits-ict.json"),
  "digital-cmos-and-vlsi-design": () => import("./digital-cmos-and-vlsi-design.json"),
  "digital-cmos-vlsi-design": () => import("./digital-cmos-vlsi-design.json"),
  "digital-communication-ece": () => import("./digital-communication-ece.json"),
  "digital-communication-ict": () => import("./digital-communication-ict.json"),
  "digital-image-processing": () => import("./digital-image-processing.json"),
  "digital-logic-and-design": () => import("./digital-logic-and-design.json"),
  "digital-logic": () => import("./digital-logic.json"),
  "digital-signal-processing-ece": () => import("./digital-signal-processing-ece.json"),
  "digital-systems-design-using-hdl-vlsi-embedded": () =>
    import("./digital-systems-design-using-hdl-vlsi-embedded.json"),
  "discipline-based-generic-optimization-techniques": () =>
    import("./discipline-based-generic-optimization-techniques.json"),
  "discrete-mathematics": () => import("./discrete-mathematics.json"),
  "discrete-maths": () => import("./discrete-maths.json"),
  "distributed-computing": () => import("./distributed-computing.json"),
  "downstream-processing": () => import("./downstream-processing.json"),
  "drilling-engineering": () => import("./drilling-engineering.json"),
  "drones-design-theory-and-applications-control": () =>
    import("./drones-design-theory-and-applications-control.json"),
  dsa: () => import("./dsa.json"),
  dsp: () => import("./dsp.json"),
  "dynamics-of-machine": () => import("./dynamics-of-machine.json"),
  "earthquake-engineering": () => import("./earthquake-engineering.json"),
  "electrical-technology-and-control-systems": () =>
    import("./electrical-technology-and-control-systems.json"),
  "electronics-devices-and-circuits-ece": () =>
    import("./electronics-devices-and-circuits-ece.json"),
  "electronics-devices-and-circuits-ict": () =>
    import("./electronics-devices-and-circuits-ict.json"),
  "element-of-civil-engg-and-mechanics": () => import("./element-of-civil-engg-and-mechanics.json"),
  "element-of-mechanical-engg": () => import("./element-of-mechanical-engg.json"),
  "elements-of-electrical-and-electronics-engineering-biotech": () =>
    import("./elements-of-electrical-and-electronics-engineering-biotech.json"),
  "elements-of-electrical-and-electronics-engineering-ce": () =>
    import("./elements-of-electrical-and-electronics-engineering-ce.json"),
  "elements-of-electrical-engg": () => import("./elements-of-electrical-engg.json"),
  "em-theory": () => import("./em-theory.json"),
  "embedded-system-design": () => import("./embedded-system-design.json"),
  "embedded-systems": () => import("./embedded-systems.json"),
  "engg-chemistry": () => import("./engg-chemistry.json"),
  "engg-graphics": () => import("./engg-graphics.json"),
  "engineering-chemistry": () => import("./engineering-chemistry.json"),
  "engineering-geology-and-soil-mechanics-with-lab": () =>
    import("./engineering-geology-and-soil-mechanics-with-lab.json"),
  "engineering-metallurgy": () => import("./engineering-metallurgy.json"),
  "environment-science-civil": () => import("./environment-science-civil.json"),
  "environment-science-ict": () => import("./environment-science-ict.json"),
  "environmental-engineering-with-lab": () => import("./environmental-engineering-with-lab.json"),
  "environmental-science-biotech": () => import("./environmental-science-biotech.json"),
  "environmental-science-petro": () => import("./environmental-science-petro.json"),
  "environmental-science": () => import("./environmental-science.json"),
  "estimation-costing-contracts-and-valuations": () =>
    import("./estimation-costing-contracts-and-valuations.json"),
  "flow-assurance": () => import("./flow-assurance.json"),
  "fluid-mechanics-and-fluid-machinery": () => import("./fluid-mechanics-and-fluid-machinery.json"),
  "fluid-mechanics": () => import("./fluid-mechanics.json"),
  "food-biotechnology": () => import("./food-biotechnology.json"),
  "foundation-and-geotechnical-applications-with-lab": () =>
    import("./foundation-and-geotechnical-applications-with-lab.json"),
  "fundamentals-of-fluid-mechanics-for-petroleum-engineers": () =>
    import("./fundamentals-of-fluid-mechanics-for-petroleum-engineers.json"),
  "fundamentals-of-ict": () => import("./fundamentals-of-ict.json"),
  "fundamentals-of-signal-processing-and-communication": () =>
    import("./fundamentals-of-signal-processing-and-communication.json"),
  "general-microbiology": () => import("./general-microbiology.json"),
  "genetic-engineering": () => import("./genetic-engineering.json"),
  "genomics-and-proteomics": () => import("./genomics-and-proteomics.json"),
  "geology-for-petroleum-engineers": () => import("./geology-for-petroleum-engineers.json"),
  "geomechanics-and-strength-of-materials": () =>
    import("./geomechanics-and-strength-of-materials.json"),
  "green-biotechnology-and-pollution-abatement": () =>
    import("./green-biotechnology-and-pollution-abatement.json"),
  "health-safety-and-environment": () => import("./health-safety-and-environment.json"),
  "heat-and-mass-transfer-me": () => import("./heat-and-mass-transfer-me.json"),
  "heat-and-mass-transfer-petro": () => import("./heat-and-mass-transfer-petro.json"),
  "highway-and-traffic-engineering-with-lab": () =>
    import("./highway-and-traffic-engineering-with-lab.json"),
  "human-anatomy-and-physiology-i": () => import("./human-anatomy-and-physiology-i.json"),
  "human-anatomy-and-physiology-ii": () => import("./human-anatomy-and-physiology-ii.json"),
  "hydrocarbon-contracts-and-asset-management": () =>
    import("./hydrocarbon-contracts-and-asset-management.json"),
  "hydrology-and-water-resources-with-lab": () =>
    import("./hydrology-and-water-resources-with-lab.json"),
  "ic-technology-vlsi-embedded": () => import("./ic-technology-vlsi-embedded.json"),
  "image-processing-communication-and-signal-processing": () =>
    import("./image-processing-communication-and-signal-processing.json"),
  "immunology-and-immunotechnology": () => import("./immunology-and-immunotechnology.json"),
  "industry-4-0-department-specific-ce": () => import("./industry-4-0-department-specific-ce.json"),
  "industry-4-0-department-specific-civil": () =>
    import("./industry-4-0-department-specific-civil.json"),
  "industry-4-0-lab-department-specific": () =>
    import("./industry-4-0-lab-department-specific.json"),
  "industry-4-0-petro": () => import("./industry-4-0-petro.json"),
  "information-theory-and-coding-communication-systems": () =>
    import("./information-theory-and-coding-communication-systems.json"),
  "integrated-reservoir-management-and-enhanced-oil-recovery": () =>
    import("./integrated-reservoir-management-and-enhanced-oil-recovery.json"),
  "internal-combustion-engine": () => import("./internal-combustion-engine.json"),
  "internet-of-things-ce": () => import("./internet-of-things-ce.json"),
  "internet-of-things-computer-systems-ece": () =>
    import("./internet-of-things-computer-systems-ece.json"),
  "internet-of-things-software-and-networks-ict": () =>
    import("./internet-of-things-software-and-networks-ict.json"),
  "introduction-to-artificial-intelligence-biotech": () =>
    import("./introduction-to-artificial-intelligence-biotech.json"),
  "introduction-to-artificial-intelligence-civil": () =>
    import("./introduction-to-artificial-intelligence-civil.json"),
  "introduction-to-artificial-intelligence-department-specific-ce": () =>
    import("./introduction-to-artificial-intelligence-department-specific-ce.json"),
  "introduction-to-artificial-intelligence-petro": () =>
    import("./introduction-to-artificial-intelligence-petro.json"),
  "introduction-to-computer-programming-1": () =>
    import("./introduction-to-computer-programming-1.json"),
  "introduction-to-computer-programming-2": () =>
    import("./introduction-to-computer-programming-2.json"),
  "introduction-to-electrical-engineering": () =>
    import("./introduction-to-electrical-engineering.json"),
  "introduction-to-robotics-control": () => import("./introduction-to-robotics-control.json"),
  "linear-integrated-circuits-and-applications": () =>
    import("./linear-integrated-circuits-and-applications.json"),
  "machine-design-i": () => import("./machine-design-i.json"),
  "machine-design-ii": () => import("./machine-design-ii.json"),
  "machine-learning-ai-ict": () => import("./machine-learning-ai-ict.json"),
  "machine-learning-and-applications-computer-systems": () =>
    import("./machine-learning-and-applications-computer-systems.json"),
  "machine-learning-ce": () => import("./machine-learning-ce.json"),
  "machine-learning-in-cyber-security": () => import("./machine-learning-in-cyber-security.json"),
  "manufacturing-process-i": () => import("./manufacturing-process-i.json"),
  "manufacturing-process-ii": () => import("./manufacturing-process-ii.json"),
  "mathematics-1-ict": () => import("./mathematics-1-ict.json"),
  "mathematics-2-ict": () => import("./mathematics-2-ict.json"),
  "mathematics-3-civil": () => import("./mathematics-3-civil.json"),
  "mathematics-for-biotechnology-i": () => import("./mathematics-for-biotechnology-i.json"),
  "mathematics-for-biotechnology-ii": () => import("./mathematics-for-biotechnology-ii.json"),
  "mathematics-i-ce-ece-civil": () => import("./mathematics-i-ce-ece-civil.json"),
  "mathematics-i-me": () => import("./mathematics-i-me.json"),
  "mathematics-i-petro": () => import("./mathematics-i-petro.json"),
  "mathematics-ii-ce-ece-civil": () => import("./mathematics-ii-ce-ece-civil.json"),
  "mathematics-ii-me": () => import("./mathematics-ii-me.json"),
  "mathematics-ii-petro": () => import("./mathematics-ii-petro.json"),
  "mathematics-iii-petro": () => import("./mathematics-iii-petro.json"),
  "maths-iii": () => import("./maths-iii.json"),
  "mechanical-measurements-and-metrology": () =>
    import("./mechanical-measurements-and-metrology.json"),
  "medical-diagnostics": () => import("./medical-diagnostics.json"),
  "metabolic-engineering": () => import("./metabolic-engineering.json"),
  "microwave-and-antenna": () => import("./microwave-and-antenna.json"),
  "mixed-signal-vlsi-design-vlsi-embedded": () =>
    import("./mixed-signal-vlsi-design-vlsi-embedded.json"),
  "mobile-application-development-software-and-networks": () =>
    import("./mobile-application-development-software-and-networks.json"),
  "mobile-computing": () => import("./mobile-computing.json"),
  "modern-control-systems-control": () => import("./modern-control-systems-control.json"),
  "modern-physics-biotech": () => import("./modern-physics-biotech.json"),
  "modern-physics-petro": () => import("./modern-physics-petro.json"),
  "modern-wireless-communication": () => import("./modern-wireless-communication.json"),
  "modern-wireless-communications-communication-and-signal": () =>
    import("./modern-wireless-communications-communication-and-signal.json"),
  "molecular-biology-and-genetics": () => import("./molecular-biology-and-genetics.json"),
  "molecular-data-analysis-and-simulations": () =>
    import("./molecular-data-analysis-and-simulations.json"),
  "nanotechnology-in-oil-and-gas-industry": () =>
    import("./nanotechnology-in-oil-and-gas-industry.json"),
  nanotechnology: () => import("./nanotechnology.json"),
  "natural-gas-engineering-and-lng-value-chain": () =>
    import("./natural-gas-engineering-and-lng-value-chain.json"),
  "natural-language-processing": () => import("./natural-language-processing.json"),
  "networks-and-systems": () => import("./networks-and-systems.json"),
  "next-generation-sequence-analysis": () => import("./next-generation-sequence-analysis.json"),
  "novel-separation-processes-dyes-and-pigments": () =>
    import("./novel-separation-processes-dyes-and-pigments.json"),
  "numerical-methods": () => import("./numerical-methods.json"),
  "object-oriented-modelling-and-design": () =>
    import("./object-oriented-modelling-and-design.json"),
  oop: () => import("./oop.json"),
  "operating-systems": () => import("./operating-systems.json"),
  "optical-communication-communication-and-signal-processing": () =>
    import("./optical-communication-communication-and-signal-processing.json"),
  "optimization-methods-and-algorithms-ai": () =>
    import("./optimization-methods-and-algorithms-ai.json"),
  "opto-electronics-and-optical-communication-communication": () =>
    import("./opto-electronics-and-optical-communication-communication.json"),
  "petroleum-exploration": () => import("./petroleum-exploration.json"),
  "petroleum-refinery-engineering": () => import("./petroleum-refinery-engineering.json"),
  "pharmaceutical-biotechnology": () => import("./pharmaceutical-biotechnology.json"),
  "pharmacokinetics-and-pharmacodynamics": () =>
    import("./pharmacokinetics-and-pharmacodynamics.json"),
  "pharmacology-of-drug-action": () => import("./pharmacology-of-drug-action.json"),
  "physics-civil": () => import("./physics-civil.json"),
  "physics-ece": () => import("./physics-ece.json"),
  "physics-ict": () => import("./physics-ict.json"),
  "physics-theory-me": () => import("./physics-theory-me.json"),
  "pipeline-engineering": () => import("./pipeline-engineering.json"),
  "power-electronics-vlsi-embedded": () => import("./power-electronics-vlsi-embedded.json"),
  "principles-of-programming-languages": () => import("./principles-of-programming-languages.json"),
  "probability-and-statistics-theory": () => import("./probability-and-statistics-theory.json"),
  "problem-solving-through-java-software-and-networks": () =>
    import("./problem-solving-through-java-software-and-networks.json"),
  "production-operation-management": () => import("./production-operation-management.json"),
  "project-management-department-elective-v": () =>
    import("./project-management-department-elective-v.json"),
  "project-management-with-lab": () => import("./project-management-with-lab.json"),
  "quantum-computing": () => import("./quantum-computing.json"),
  "radar-and-navigation-systems-communication-systems": () =>
    import("./radar-and-navigation-systems-communication-systems.json"),
  "refrigeration-and-air-conditioning": () => import("./refrigeration-and-air-conditioning.json"),
  "reservoir-engineering": () => import("./reservoir-engineering.json"),
  "reservoir-modelling-and-simulation": () => import("./reservoir-modelling-and-simulation.json"),
  "rf-engineering": () => import("./rf-engineering.json"),
  robotics: () => import("./robotics.json"),
  "satellite-communication-communication-systems": () =>
    import("./satellite-communication-communication-systems.json"),
  "secure-software-engineering": () => import("./secure-software-engineering.json"),
  "sedimentary-and-petroleum-geology": () => import("./sedimentary-and-petroleum-geology.json"),
  "soft-computing": () => import("./soft-computing.json"),
  "software-engineering-methodology": () => import("./software-engineering-methodology.json"),
  "software-engineering": () => import("./software-engineering.json"),
  "solid-mechanics": () => import("./solid-mechanics.json"),
  "speech-processing": () => import("./speech-processing.json"),
  "statistical-signal-processing-communication-and-signal": () =>
    import("./statistical-signal-processing-communication-and-signal.json"),
  "stem-cell-technology": () => import("./stem-cell-technology.json"),
  "strength-of-materials": () => import("./strength-of-materials.json"),
  "structural-analysis": () => import("./structural-analysis.json"),
  "surface-and-offshore-production-operations": () =>
    import("./surface-and-offshore-production-operations.json"),
  "surveying-practices-with-lab": () => import("./surveying-practices-with-lab.json"),
  "synthetic-and-systems-biology": () => import("./synthetic-and-systems-biology.json"),
  "theory-of-computation-and-compiler-design": () =>
    import("./theory-of-computation-and-compiler-design.json"),
  "theory-of-computation": () => import("./theory-of-computation.json"),
  "thermal-engineering-and-power-plant": () => import("./thermal-engineering-and-power-plant.json"),
  "thermodynamics-and-fluid-flow": () => import("./thermodynamics-and-fluid-flow.json"),
  "thermodynamics-of-petroleum-reservoir-fluids": () =>
    import("./thermodynamics-of-petroleum-reservoir-fluids.json"),
  "tissue-engineering-and-regenerative-medicine": () =>
    import("./tissue-engineering-and-regenerative-medicine.json"),
  "ui-ux-design": () => import("./ui-ux-design.json"),
  "unconventional-hydrocarbon-energy-resources": () =>
    import("./unconventional-hydrocarbon-energy-resources.json"),
  "web-and-mobile-development-essentials": () =>
    import("./web-and-mobile-development-essentials.json"),
  "web-application-testing": () => import("./web-application-testing.json"),
  "web-technology-software-and-networks": () =>
    import("./web-technology-software-and-networks.json"),
  "well-completion-and-fundamentals-of-production-engineering": () =>
    import("./well-completion-and-fundamentals-of-production-engineering.json"),
  "well-logging": () => import("./well-logging.json"),
  "well-stimulation-and-artificial-lift-techniques": () =>
    import("./well-stimulation-and-artificial-lift-techniques.json"),
  "well-test-analysis": () => import("./well-test-analysis.json"),
  "wireless-sensor-networks": () => import("./wireless-sensor-networks.json"),
};
